universe = container
container_image = docker://nicolaka/netshoot:v0.15
executable = execution/job-scripts/test_transfer_a.sh

log    = /home/lucas.ferguson/ospool-manager/logs/test_a.$(ClusterId).log
output = /home/lucas.ferguson/ospool-manager/logs/test_a.$(ClusterId).out
error  = /home/lucas.ferguson/ospool-manager/logs/test_a.$(ClusterId).err

stream_output = true
stream_error  = true

request_cpus   = 1
request_memory = 512 MB
request_disk   = 1 GB

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = execution/job-scripts/test_transfer_a.sh

# NO remap — output goes to schedd spool, retrieve with: ospool fetch <cluster_id>
transfer_output_files = result.txt


queue 1
