universe = container
container_image = docker://nicolaka/netshoot:v0.15
executable = execution/job-scripts/test_transfer_b.sh

log    = /home/lucas.ferguson/ospool-manager/logs/test_b.$(ClusterId).log
output = /home/lucas.ferguson/ospool-manager/logs/test_b.$(ClusterId).out
error  = /home/lucas.ferguson/ospool-manager/logs/test_b.$(ClusterId).err

stream_output = true
stream_error  = true

request_cpus   = 1
request_memory = 512 MB
request_disk   = 1 GB

should_transfer_files   = YES
when_to_transfer_output = ON_EXIT
transfer_input_files    = execution/job-scripts/test_transfer_b.sh

OSDF_BASE = osdf:///ospool/ap40/data/lucas.ferguson
transfer_output_files = result.txt
transfer_output_remaps = "result.txt=$(OSDF_BASE)/outputs/result_b_$(ClusterId).txt"

queue 1
